### PR TITLE
Add firewall protecting private subnet.

### PR DESCRIPTION
**Pull request by mrichardson03**
Adds private subnet to VPC, with PAN-OS firewall between them that is configured via bootstrap.

### CODE REVIEW

**Comment by mrichardson03** [comment]
I'd really recommend changing the CI config to have AWS credentials specified as environment variables instead of statically defined in the config.

**Comment by hotpeppersec** [comment]
> I'd really recommend changing the CI config to have AWS credentials specified as environment variables instead of statically defined in the config.

Cool I will make the change in this PR if that's OK.

**Comment by mrichardson03** [comment]
Works for me.

**Comment by hotpeppersec** [comment]
> Works for me.

It won't let me push to your PR, I will just do the change and merge it and then we can pull it into this one I guess. 

```
fdiaz at REMMAC11ELVDT ~ 🍕  git push mrichardson03 mrichardson03/add_firewall          workflows
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (5/5), 499 bytes | 499.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:mrichardson03/ctf_scoreboard.git
 ! [remote rejected] mrichardson03/add_firewall -> mrichardson03/add_firewall (permission denied)
error: failed to push some refs to 'git@github.com:mrichardson03/ctf_scoreboard.git'
```

**Pull request merged**
